services:
  capotokeys:
    image: ghcr.io/reprodev/capotokeys:v1.0
    container_name: capotokeys
    ports:
      - "4506:4506"
    volumes:
      - ./appdata/config/capotokeys:/data
    restart: unless-stopped
